// // components/store/medicineapi.js
// components/store/medicineapi.js
import axios from 'axios';

const API_URL = 'https://mocki.io/v1/4f2507ad-0300-43b5-a2e7-411143b171f0';

export const fetchMedicines = async () => {
  try {
    const response = await axios.get(API_URL);
    return response.data; // returns array of products
  } catch (error) {
    console.error('Error fetching products:', error);
    return [];
  }
};

// export const data1 = {
//   "top-10-health-supplements": [
//     {
//       id: 1,
//       name: "2blink Eye Drop 15ml",
//       img: "/asset/medicine/2blink_Eye_Drop_15ml.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture. Can be used with contact lenses.",
//       category: "Health Supplements",
//       type: "Eye Drop",
//       price: 479,
//       stock: 50,
//     },
//     {
//       id: 2,
//       name: "2sum 1gm Injection",
//       img: "/asset/medicine/2.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture. Can be used with contact lenses.",
//       category: "Health Supplements",
//       type: "Injection",
//       price: 469,
//       stock: 30,
//     },
//     {
//       id: 3,
//       name: "3d Ultra Tablets",
//       img: "/asset/medicine/5.webp",
//       description: "Relieves pain and reduces fever. Long-lasting effect.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 699,
//       stock: 40,
//     },
//     {
//       id: 4,
//       name: "A2a 100mg Tablets",
//       img: "/asset/medicine/6.webp",
//       description:
//         "Reduces pain and inflammation. Can be used with contact lenses.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 599,
//       stock: 45,
//     },
//     {
//       id: 5,
//       name: "Abacus 100mg Tablets 10s",
//       img: "/asset/medicine/9.webp",
//       description: "Helps relieve muscle pain. Reduces fever.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 399,
//       stock: 20,
//     },
//     {
//       id: 6,
//       name: "2sum 500gm Injection",
//       img: "/asset/medicine/4.webp",
//       description: "Hydrates and lubricates dry eyes.",
//       category: "Health Supplements",
//       type: "Injection",
//       price: 529,
//       stock: 60,
//     },
//     {
//       id: 7,
//       name: "A2a 50mg Tablets",
//       img: "/asset/medicine/8.webp",
//       description: "Provides moisture and relief for dry eyes.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 449,
//       stock: 35,
//     },
//     {
//       id: 8,
//       name: "2blink Eye Drop 10ml",
//       img: "/asset/medicine/2blink_Eye_Drop_10ml.webp",
//       description: "Lubricates and hydrates dry eyes.",
//       category: "Health Supplements",
//       type: "Eye Drop",
//       price: 289,
//       stock: 50,
//     },
//     {
//       id: 9,
//       name: "Med-x 1gm Injection",
//       img: "/asset/medicine/med-x.webp",
//       description: "Relieves muscle pain and stiffness.",
//       category: "Health Supplements",
//       type: "Injection",
//       price: 459,
//       stock: 40,
//     },
//     {
//       id: 10,
//       name: "Pain-Relief Tablets",
//       img: "/asset/medicine/pain-relief.webp",
//       description: "Eases body aches and reduces fever.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 349,
//       stock: 25,
//     },
//     {
//       id: 11,
//       name: "Joint Care Tablets",
//       img: "/asset/medicine/joint-care.webp",
//       description: "Supports joint flexibility and mobility.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 749,
//       stock: 30,
//     },
//     {
//       id: 12,
//       name: "Vitamin C Tablets 1000mg",
//       img: "/asset/medicine/vitamin-c.webp",
//       description: "Boosts immunity and fights infections.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 199,
//       stock: 55,
//     },
//     {
//       id: 13,
//       name: "Omega 3 Capsules",
//       img: "/asset/medicine/omega-3.webp",
//       description: "Supports heart health and brain function.",
//       category: "Health Supplements",
//       type: "Capsule",
//       price: 329,
//       stock: 60,
//     },
//     {
//       id: 14,
//       name: "Magnesium Tablets 250mg",
//       img: "/asset/medicine/magnesium.webp",
//       description: "Promotes muscle and nerve function.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 249,
//       stock: 40,
//     },
//     {
//       id: 15,
//       name: "Calcium Tablets 500mg",
//       img: "/asset/medicine/calcium.webp",
//       description: "Strengthens bones and teeth.",
//       category: "Health Supplements",
//       type: "Tablet",
//       price: 399,
//       stock: 50,
//     },
//   ],
//   skincare: [
//     {
//       id: 1,
//       name: "Abacus 100mg Tablets 10s",
//       img: "/asset/medicine/10.webp",
//       description: "Hydrates and moisturizes dry skin.",
//       category: "Skincare",
//       type: "Tablet",
//       price: 809,
//       stock: 25,
//     },
//     {
//       id: 2,
//       name: "A2a 25mg Tablets",
//       img: "/asset/medicine/7.webp",
//       description: "Promotes healthy skin. Reduces inflammation.",
//       category: "Skincare",
//       type: "Tablet",
//       price: 469,
//       stock: 15,
//     },
//     {
//       id: 3,
//       name: "Vitamin E Cream",
//       img: "/asset/medicine/vitamin-e-cream.webp",
//       description: "Nourishes and repairs damaged skin.",
//       category: "Skincare",
//       type: "Cream",
//       price: 699,
//       stock: 40,
//     },
//     {
//       id: 4,
//       name: "Tea Tree Oil",
//       img: "/asset/medicine/tea-tree-oil.webp",
//       description: "Heals acne and promotes clear skin.",
//       category: "Skincare",
//       type: "Oil",
//       price: 249,
//       stock: 35,
//     },
//     {
//       id: 5,
//       name: "Anti-Aging Serum",
//       img: "/asset/medicine/anti-aging-serum.webp",
//       description: "Reduces wrinkles and restores skin elasticity.",
//       category: "Skincare",
//       type: "Serum",
//       price: 999,
//       stock: 20,
//     },
//     {
//       id: 6,
//       name: "Hydrating Face Mask",
//       img: "/asset/medicine/hydrating-mask.webp",
//       description: "Moisturizes and refreshes dry skin.",
//       category: "Skincare",
//       type: "Face Mask",
//       price: 399,
//       stock: 50,
//     },
//     {
//       id: 7,
//       name: "Exfoliating Scrub",
//       img: "/asset/medicine/exfoliating-scrub.webp",
//       description: "Removes dead skin cells and unclogs pores.",
//       category: "Skincare",
//       type: "Scrub",
//       price: 199,
//       stock: 30,
//     },
//     {
//       id: 8,
//       name: "Hydrating Face Lotion",
//       img: "/asset/medicine/hydrating-lotion.webp",
//       description: "Soothes and moisturizes the skin.",
//       category: "Skincare",
//       type: "Lotion",
//       price: 599,
//       stock: 45,
//     },
//     {
//       id: 9,
//       name: "Cleansing Facial Wash",
//       img: "/asset/medicine/cleansing-facial-wash.webp",
//       description: "Removes dirt and oil without drying.",
//       category: "Skincare",
//       type: "Wash",
//       price: 349,
//       stock: 25,
//     },
//     {
//       id: 10,
//       name: "Collagen Serum",
//       img: "/asset/medicine/collagen-serum.webp",
//       description: "Promotes youthful and radiant skin.",
//       category: "Skincare",
//       type: "Serum",
//       price: 799,
//       stock: 60,
//     },
//     {
//       id: 11,
//       name: "Aloe Vera Gel",
//       img: "/asset/medicine/aloe-vera-gel.webp",
//       description: "Heals and moisturizes dry skin.",
//       category: "Skincare",
//       type: "Gel",
//       price: 299,
//       stock: 50,
//     },
//     {
//       id: 12,
//       name: "Face Moisturizer",
//       img: "/asset/medicine/face-moisturizer.webp",
//       description: "Hydrates and protects your skin.",
//       category: "Skincare",
//       type: "Moisturizer",
//       price: 499,
//       stock: 55,
//     },
//     {
//       id: 13,
//       name: "Hand Cream",
//       img: "/asset/medicine/hand-cream.webp",
//       description: "Moisturizes and softens hands.",
//       category: "Skincare",
//       type: "Cream",
//       price: 249,
//       stock: 40,
//     },
//     {
//       id: 14,
//       name: "Night Repair Cream",
//       img: "/asset/medicine/night-repair-cream.webp",
//       description: "Repairs and rejuvenates skin overnight.",
//       category: "Skincare",
//       type: "Cream",
//       price: 699,
//       stock: 30,
//     },
//     {
//       id: 15,
//       name: "Sunblock SPF 50+",
//       img: "/asset/medicine/sunblock-spf50.webp",
//       description: "Protects skin from harmful UV rays.",
//       category: "Skincare",
//       type: "Sunscreen",
//       price: 399,
//       stock: 60,
//     },
//   ],
//   electronics: [
//     {
//       id: 1,
//       name: "2sum 1gm Injection",
//       img: "/asset/medicine/2.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture.",
//       category: "Electronics",
//       type: "Injection",
//       price: 469,
//       stock: 50,
//     },
//     {
//       id: 2,
//       name: "3d Ultra Tablets",
//       img: "/asset/medicine/5.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture.",
//       category: "Electronics",
//       type: "Tablet",
//       price: 909,
//       stock: 20,
//     },
//     {
//       id: 3,
//       name: "Smart Watch Series 5",
//       img: "/asset/medicine/smart-watch.webp",
//       description: "Tracks heart rate and monitors sleep patterns.",
//       category: "Electronics",
//       type: "Smart Watch",
//       price: 5999,
//       stock: 30,
//     },
//     {
//       id: 4,
//       name: "Wireless Earbuds",
//       img: "/asset/medicine/wireless-earbuds.webp",
//       description: "High-quality sound and noise cancellation.",
//       category: "Electronics",
//       type: "Earbuds",
//       price: 1499,
//       stock: 50,
//     },
//     {
//       id: 5,
//       name: "Bluetooth Speaker",
//       img: "/asset/medicine/bluetooth-speaker.webp",
//       description: "Portable with superior sound quality.",
//       category: "Electronics",
//       type: "Speaker",
//       price: 899,
//       stock: 40,
//     },
//     {
//       id: 6,
//       name: "Noise Cancelling Headphones",
//       img: "/asset/medicine/noise-cancelling-headphones.webp",
//       description: "Blocks out external noise for an immersive experience.",
//       category: "Electronics",
//       type: "Headphones",
//       price: 1999,
//       stock: 25,
//     },
//     {
//       id: 7,
//       name: "4K UHD Smart TV",
//       img: "/asset/medicine/4k-smart-tv.webp",
//       description: "Stunning picture quality with HDR.",
//       category: "Electronics",
//       type: "Smart TV",
//       price: 14999,
//       stock: 15,
//     },
//     {
//       id: 8,
//       name: "Laptop Pro Max 15",
//       img: "/asset/medicine/laptop-pro-max.webp",
//       description: "High-performance laptop with advanced features.",
//       category: "Electronics",
//       type: "Laptop",
//       price: 54999,
//       stock: 20,
//     },
//     {
//       id: 9,
//       name: "Gaming Mouse",
//       img: "/asset/medicine/gaming-mouse.webp",
//       description: "Precise tracking for gaming enthusiasts.",
//       category: "Electronics",
//       type: "Mouse",
//       price: 799,
//       stock: 50,
//     },
//     {
//       id: 10,
//       name: "Portable Power Bank",
//       img: "/asset/medicine/power-bank.webp",
//       description: "Charge your devices on the go.",
//       category: "Electronics",
//       type: "Power Bank",
//       price: 999,
//       stock: 35,
//     },
//     {
//       id: 11,
//       name: "Smartphone 12 Pro",
//       img: "/asset/medicine/smartphone.webp",
//       description: "Latest smartphone with advanced features.",
//       category: "Electronics",
//       type: "Smartphone",
//       price: 9999,
//       stock: 40,
//     },
//     {
//       id: 12,
//       name: "Bluetooth Headphones",
//       img: "/asset/medicine/bluetooth-headphones.webp",
//       description: "Wireless headphones with great sound quality.",
//       category: "Electronics",
//       type: "Headphones",
//       price: 1299,
//       stock: 45,
//     },
//     {
//       id: 13,
//       name: "LED Desk Lamp",
//       img: "/asset/medicine/led-desk-lamp.webp",
//       description: "Provides adjustable lighting for your workspace.",
//       category: "Electronics",
//       type: "Lamp",
//       price: 799,
//       stock: 30,
//     },
//     {
//       id: 14,
//       name: "Tablet Pro 10",
//       img: "/asset/medicine/tablet-pro.webp",
//       description: "Lightweight tablet with advanced features.",
//       category: "Electronics",
//       type: "Tablet",
//       price: 12999,
//       stock: 25,
//     },
//     {
//       id: 15,
//       name: "Smart Refrigerator",
//       img: "/asset/medicine/smart-fridge.webp",
//       description: "Smart refrigerator with energy-efficient features.",
//       category: "Electronics",
//       type: "Fridge",
//       price: 24999,
//       stock: 15,
//     },
//   ],
//   vitamins: [
//     {
//       id: 1,
//       name: "2sum 2gm Injection",
//       img: "/asset/medicine/3.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture.",
//       category: "Vitamins",
//       type: "Injection",
//       price: 469,
//       stock: 40,
//     },
//     {
//       id: 2,
//       name: "Abacus 100mg Tablets 10s",
//       img: "/asset/medicine/10.webp",
//       description:
//         "Lubricates and hydrates dry eyes. Provides long-lasting moisture.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 809,
//       stock: 30,
//     },
//     {
//       id: 3,
//       name: "Vitamin C Tablets",
//       img: "/asset/medicine/vitamin-c.webp",
//       description: "Boosts immunity and supports the skin.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 299,
//       stock: 50,
//     },
//     {
//       id: 4,
//       name: "Omega 3 Capsules",
//       img: "/asset/medicine/omega-3.webp",
//       description: "Supports heart health and brain function.",
//       category: "Vitamins",
//       type: "Capsule",
//       price: 329,
//       stock: 40,
//     },
//     {
//       id: 5,
//       name: "Vitamin E Capsules",
//       img: "/asset/medicine/vitamin-e-capsules.webp",
//       description: "Promotes healthy skin and protects cells.",
//       category: "Vitamins",
//       type: "Capsule",
//       price: 399,
//       stock: 45,
//     },
//     {
//       id: 6,
//       name: "Vitamin D Tablets",
//       img: "/asset/medicine/vitamin-d-tablets.webp",
//       description: "Supports bone health and immune function.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 499,
//       stock: 30,
//     },
//     {
//       id: 7,
//       name: "Biotin Tablets",
//       img: "/asset/medicine/biotin-tablets.webp",
//       description: "Promotes healthy hair and nails.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 199,
//       stock: 60,
//     },
//     {
//       id: 8,
//       name: "Multivitamin Capsules",
//       img: "/asset/medicine/multivitamin-capsules.webp",
//       description: "Provides essential nutrients for overall health.",
//       category: "Vitamins",
//       type: "Capsule",
//       price: 399,
//       stock: 50,
//     },
//     {
//       id: 9,
//       name: "Iron Supplements",
//       img: "/asset/medicine/iron-supplements.webp",
//       description: "Supports red blood cell production and energy.",
//       category: "Vitamins",
//       type: "Capsule",
//       price: 199,
//       stock: 45,
//     },
//     {
//       id: 10,
//       name: "Zinc Tablets",
//       img: "/asset/medicine/zinc-tablets.webp",
//       description: "Boosts immunity and promotes healthy skin.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 149,
//       stock: 35,
//     },
//     {
//       id: 11,
//       name: "Vitamin A Capsules",
//       img: "/asset/medicine/vitamin-a.webp",
//       description: "Supports eye health and immune function.",
//       category: "Vitamins",
//       type: "Capsule",
//       price: 279,
//       stock: 40,
//     },
//     {
//       id: 12,
//       name: "Folic Acid Tablets",
//       img: "/asset/medicine/folic-acid.webp",
//       description: "Essential for cell growth and development.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 249,
//       stock: 50,
//     },
//     {
//       id: 13,
//       name: "Calcium Tablets",
//       img: "/asset/medicine/calcium-tablets.webp",
//       description: "Supports bone health and muscle function.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 199,
//       stock: 30,
//     },
//     {
//       id: 14,
//       name: "Magnesium Tablets",
//       img: "/asset/medicine/magnesium-tablets.webp",
//       description: "Supports muscle and nerve function.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 249,
//       stock: 35,
//     },
//     {
//       id: 15,
//       name: "Potassium Tablets",
//       img: "/asset/medicine/potassium-tablets.webp",
//       description: "Supports heart health and muscle function.",
//       category: "Vitamins",
//       type: "Tablet",
//       price: 279,
//       stock: 50,
//     },
//   ],
// };
